### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by jmid** [tarides/runtime_events_tools#21]
I wanted to experiment with the `gc-stats` and so pinned the yet-to-be-opam-merged 0.4.0:
```
$ opam pin https://github.com/tarides/runtime_events_tools.git#0.4.0
runtime_events_tools is now pinned to git+https://github.com/tarides/runtime_events_tools.git#0.4.0 (version 0.3)
...
∗ installed runtime_events_tools.0.3
Done.
$
```
This is obviously minor as the package installs and runs nicely, however the version numbering seems off... :grimacing:

I suspect adding an explicit `(version "0.4.0")` to `dune-project` and regenerating the opam-file would cut it.
From a quick look I couldn't find the source of the `0.3` that `opam` picks up and reports above. :thinking:

**Comment by Sudha247** [comment]
Thanks for reporting @jmid! I'm not sure what the source of `0.3` is either. Will try regenerating the `opam` file.
